minimal_mistakes_skin    : "default" #remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-scholar
scholar:
  source: _bibliography
  bibliography: publications.bib
  bibliography_template: publication
  sort_by: year
  order: descending
title: Huix-Rotllant Research Group
description:
google_analytics:
collections:
  news:
    output: false
  people:
    output: false
